#!/bin/sh

# Configure testing environment
# https://neovim.io/doc/user/starting.html#base-directories

# CONFIG DIRECTORY
export XDG_CONFIG_HOME='test/xdg/config/'
mkdir -p ${XDG_CONFIG_HOME}
# DATA DIRECTORY
export XDG_DATA_HOME='test/xdg/local/share/'
mkdir -p ${XDG_DATA_HOME}
# STATE DIRECTORY
export XDG_STATE_HOME='test/xdg/local/state/'
mkdir -p ${XDG_STATE_HOME}
# CACHE DIRECTORY
export XDG_CACHE_HOME='test/xdg/cache/'
mkdir -p ${XDG_CACHE_HOME}
# LOG FILE
export XDG_LOG_FILE='test/xdg/local/state/nvim/log'
mkdir -p ${XDG_LOG_FILE}

# $@ is any arguments
echo $@
nvim --cmd 'set loadplugins' -l $@
# exit_code=$?
# rm ${XDG_DATA_HOME}/nvim/site/pack/testing/start/
#
# exit $exit_code
